---
- name: Post Kernel patch Check
  hosts: all
  gather_facts: false

  tasks:
  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:
      reboot_timeout: 300

  - name: Wait for connection
    ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 120
